import { StyleSheet } from 'react-native';
import { colors, font, radius, spacing } from '../../theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  header: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  title: {
    color: colors.yellow,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 2,
    marginBottom: spacing.md,
  },
  chips: { flexDirection: 'row', flexWrap: 'wrap' },
  diceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  dieBox: {
    width: 62,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  dieValue: { color: colors.text, fontSize: 20, fontWeight: '800' },
  dieLabel: { color: colors.textFaint, fontSize: font.tiny, letterSpacing: 1 },
  diceButtonWrap: { flex: 1, alignItems: 'flex-end' },
  diceButton: {
    color: colors.yellow,
    fontSize: font.small,
    fontWeight: '800',
    letterSpacing: 1.5,
    borderWidth: 1,
    borderColor: colors.yellow,
    borderRadius: radius.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    overflow: 'hidden',
  },
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  tableHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tableTitle: {
    color: colors.text,
    fontSize: font.heading,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  tableDie: { color: colors.yellow, fontSize: font.small, fontWeight: '800' },
  entries: { marginTop: spacing.md },
  entry: { flexDirection: 'row', marginBottom: spacing.sm },
  entryRoll: {
    color: colors.yellow,
    fontSize: font.small,
    fontWeight: '800',
    width: 26,
  },
  entryText: {
    color: colors.text,
    fontSize: font.small,
    lineHeight: 19,
    flex: 1,
  },
  hint: { color: colors.textFaint, fontSize: font.tiny, marginTop: spacing.xs },
  body: {
    color: colors.textDim,
    fontSize: font.small,
    lineHeight: 19,
    marginTop: 2,
  },
  benefit: {
    borderLeftWidth: 2,
    borderLeftColor: colors.yellow,
    paddingLeft: spacing.md,
    marginTop: spacing.md,
  },
  benefitName: {
    color: colors.text,
    fontSize: font.small,
    fontWeight: '800',
    letterSpacing: 1,
  },
  subLabel: {
    color: colors.textDim,
    fontSize: font.tiny,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  formulaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: spacing.xs,
  },
  formulaLabel: { color: colors.textDim, fontSize: font.small, flex: 1 },
  formulaValue: {
    color: colors.yellow,
    fontSize: font.small,
    fontWeight: '700',
    flexShrink: 1,
    textAlign: 'right',
  },
  searchWrap: {paddingHorizontal: spacing.lg},
  bullet: {
    color: colors.textDim,
    fontSize: font.small,
    lineHeight: 19,
    marginBottom: spacing.xs,
  },
});
