import { StyleSheet } from 'react-native';
import { colors, font, radius, spacing } from '../../theme';

export const styles = StyleSheet.create({
  stepBar: {
    flexDirection: 'row',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  stepDot: {
    flex: 1,
    height: 4,
    backgroundColor: colors.surfaceAlt,
    marginRight: spacing.xs,
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotActive: { backgroundColor: colors.yellow },
  stepNum: { display: 'none' },
  stepNumActive: { display: 'none' },
  stepTitle: {
    color: colors.text,
    fontSize: font.heading,
    fontWeight: '800',
    letterSpacing: 1.5,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  content: { padding: spacing.lg, paddingBottom: spacing.xxl },
  spacer: { height: spacing.md },
  help: { color: colors.textDim, fontSize: font.small, lineHeight: 18 },
  bonusBanner: {
    borderWidth: 1,
    borderColor: colors.violet,
    backgroundColor: 'rgba(155, 93, 229, 0.12)',
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
  },
  bonusBannerText: {
    color: colors.text,
    fontSize: font.small,
    lineHeight: 18,
  },
  bonusBannerAccent: {
    color: colors.violet,
    fontWeight: '800',
  },
  sum: {
    color: colors.yellow,
    fontSize: font.body,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: spacing.md,
  },
  row: { flexDirection: 'row', flexWrap: 'wrap' },
  row2: { flexDirection: 'row' },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  half: { flex: 1, marginRight: spacing.sm },
  label: {
    color: colors.textDim,
    fontSize: font.tiny,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: spacing.xs,
  },
  originCard: { borderColor: colors.border },
  originCardActive: { borderColor: colors.yellow },
  originName: {
    color: colors.text,
    fontSize: font.heading,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  originNameActive: { color: colors.yellow },
  originDesc: {
    color: colors.textDim,
    fontSize: font.small,
    lineHeight: 18,
    marginTop: spacing.xs,
    marginBottom: spacing.md,
  },
  benefitsLabel: {
    color: colors.textFaint,
    fontSize: font.tiny,
    letterSpacing: 1.2,
    marginBottom: spacing.sm,
  },
  benefit: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  benefitActive: {
    borderColor: colors.yellow,
    backgroundColor: colors.surfaceAlt,
  },
  benefitName: {
    color: colors.text,
    fontSize: font.small,
    fontWeight: '800',
    letterSpacing: 1,
  },
  benefitNameActive: { color: colors.yellow },
  benefitDesc: {
    color: colors.textDim,
    fontSize: font.small,
    lineHeight: 17,
    marginTop: 2,
  },
  rolled: { marginBottom: spacing.lg },
  rolledInput: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    fontSize: font.body,
    lineHeight: 19,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.sm,
  },
  rolledInputMultiline: { minHeight: 76, textAlignVertical: 'top' },
  rolledActions: { flexDirection: 'row', flexWrap: 'wrap' },
  optionDesc: {
    color: colors.textFaint,
    fontSize: font.small,
    lineHeight: 16,
    marginTop: spacing.xs,
  },
  option: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  optionActive: {
    borderColor: colors.yellow,
    backgroundColor: colors.surfaceAlt,
  },
  optionRoll: {
    color: colors.yellow,
    fontSize: font.small,
    fontWeight: '800',
    width: 22,
  },
  optionText: {
    color: colors.text,
    fontSize: font.small,
    lineHeight: 18,
    flex: 1,
  },
  footer: {
    color: colors.textFaint,
    fontSize: font.tiny,
    letterSpacing: 1,
    textAlign: 'center',
    marginVertical: spacing.lg,
  },
  footerBar: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    padding: spacing.md,
    backgroundColor: colors.surface,
  },
  footerButton: { flex: 1, marginRight: spacing.sm },
});
